name: full_course
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_bloc: ^8.1.6
  fpdart: ^1.1.0
  get_it: ^8.0.0
  supabase_flutter: ^2.7.0
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  uuid: ^4.5.1
  intl: ^0.19.0
  internet_connection_checker_plus: ^2.5.2
  app_settings: ^5.1.1

  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
