include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # 규칙을 켜거나 끌 수 있습니다.
    avoid_print: true # print() 대신 logging 패키지 사용
    prefer_const_constructors: true # 가능한 곳에 const 생성자 사용
    prefer_final_locals: true # 로컬 변수에 final 사용
    curly_braces_in_flow_control_structures: true # 조건문 등에 중괄호 사용
    always_declare_return_types: true # 함수 및 메서드에 반환형 명시
    annotate_overrides: true # @override를 사용한 메서드 명시
    prefer_single_quotes: true # 문자열 리터럴에 단일 따옴표 사용
    prefer_typing_uninitialized_variables: true # 초기화되지 않은 변수에 타입 명시
    lines_longer_than_80_chars: true # 한줄의 최대 길이를 80글자로 설정

analyzer:
  exclude: # 자동 생성된 코드는 코드 분석에서 제외하여 분석 시간 단축
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  errors:
    # 특정 규칙에 대해 경고나 에러 레벨을 조정
    missing_return: error
    dead_code: warning
    unused_local_variable: warning
    unused_import: warning
