name: todo_bloc_retrofit
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  hexcolor: ^3.0.1
  connectivity_plus: ^6.0.5
  retrofit: ^4.4.1
  dio: ^5.7.0

  flutter_bloc: ^8.1.6
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.3

flutter:
  uses-material-design: true
